### ISSUE TITLE
Points vs Vectors

### ISSUE THREAD

**Issue by useronym** [noinia/hgeometry#176]
Hi! Thanks for this great library, I really enjoy the amount of useful stuff that's in here.

I'm wondering, what is the motivation for distinguishing between `Point` and `Vector`? It seems like having two different representations of pretty much the same thing is making parts of the API a bit unwieldy.

In addition, basic operations on `Point`s are missing, as `Point` does not have an instance for `Metric` (something that `Vector` does). Is there a reason for not including basic operations on points (such as addition and multiplication by constant)?

**Comment by noinia** [comment]
I would argue that Points and Vectors are really different things/objects that just happen to have the same representation. E.g. in the same way that Age and "The number of people in country X" are both natural numbers/integers, but we would probably define newtypes 'Age' and 'NumberOfPeople' to prevent accidentally passing an Age to a function that expects the number of inhabitants of a country.

As for why points don't have a Metric instance: that is intentional, since I don't think it actually makes sense to try to add points, or compute their dot products.  (i.e. what does the dot product of two points mean?). You are right that when implementing some primitives this means we need to do some unpacking here and there. But I hope that in time we will have most primitives implemented so that you can express what it is you want by just composing existing operations.

**Comment by useronym** [comment]
I think those are fair concerns. I would argue that one of the reasons for the power of vectors is that they can be used to describe **both** positions and offsets.

As an example consider the snipped below that constructs an equilateral triangle with a given size, center, and rotation.

```haskell
equiTriangle :: (Show a, Floating a) => a -> Point 2 a -> a -> Triangle 2 () a
equiTriangle size center rot = Triangle' (toPoint2 (cv ^+^ a)) (toPoint2 (cv ^+^ b)) (toPoint2 (cv ^+^ c))
  where
    cv = toVector2 center
    a = transformBy (rotation rot) (Vector2 0 size)
    b = r a
    c = r b
    r = transformBy (rotation 2.0943951)
```

One could write it like this instead:
```haskell
equiTriangle :: (Show a, Floating a) => a -> Point 2 a -> a -> Triangle 2 () a
equiTriangle size center rot = Triangle' a' b' c'
  where
    cv = toVector2 center
    a = transformBy (rotation rot) (Vector2 0 size)
    b = r a
    c = r b
    a' = transformBy (translation a) center
    b' = transformBy (translation b) center
    c' = transformBy (translation c) center
    r = transformBy (rotation 2.0943951)
```
However this is a lot more verbose and, to me, seems to obscure to an extent what is actually going on.

Not saying that there's necessarily something wrong with your argument, but as someone currently working with real-time 3D graphics, I am very used to utilizing vectors for describing positions, offsets, and directions. This gives a lot of flexibility in combining these, e.g. to offset a position, scale it, or move it along a direction. You can of course do all of those with transformation matrices, but sometimes you don't need all the power of affine functions. Just my personal view, feel free to close this issue :)

**Comment by noinia** [comment]
Are you aware that you could write: 

```haskell
equiTriangle :: (Show a, Floating a) => a -> Point 2 a -> a -> Triangle 2 () a
equiTriangle size center rot = Triangle' (center .+^ a) (center .+^ b) (center .+^ c)
  where
    a = transformBy (rotation rot) (Vector2 0 size)
    b = r a
    c = r b
    r = transformBy (rotation 2.0943951)
```

**Comment by useronym** [comment]
Ah! I was not aware of that, that addresses the example nicely. There's a bit of an operator hell thing going on here where there's many different operators that essentially do the same thing, just on different types. But that's more of a Haskell issue I suppose.

I'll close this issue now. Thanks!
