### ISSUE TITLE
stack.yaml versions

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [noinia/hgeometry#19]
Does there really need to be different stack.yaml files for the different ghc versions?

**Comment by noinia** [comment]
The stack files are used (only) to run the tests in travis. I do think it is a good idea to test the library using multiple ghc versions (since ghc is releasing new versions at a pretty high pace), but if you have an other easy way of setting that up that is fine by me as well. (I'm currently using pakcheck to set this up).

**Comment by noinia** [comment]
Since the answer is basically yes I'm closing this.
