### ISSUE TITLE
hgeometry-core

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [noinia/hgeometry#23]
I'm working on extracting the core geometric types  
https://github.com/BebeSparkelSparkel/hgeometry/tree/extract-core

I think the below belong in core
- Boundary
- Box
- HalfLine
- HyperPlane
- Interval
- Line
- Point
- PolyLine
- Polygon
- Properties.hs
- SegmentTree.hs
- SubLine
- Transformation
- Triangle
- Vector

I am unsure if the below belong in core:
- Slab
- SegmentTree
- KDTree
- IntervalTree
- Envelope
- Duality
- Arrangement
  - Not sure what to do with src/Data/Geometry/Arrangement since it depends on Data.Geometry.PlanarSubdivision. I don't think that PlanarSubdivision belongs in core, but let me know what you think.

**Comment by noinia** [comment]
Hmm, good question. I think we should have clear idea what the intended goal of all the sub-packages is going to be. I.e. is 'hgeometry-core' just going to be the minimal set of modules required by some of the other sub-packages like 'hgeometry-ipe', or is it intended to be "a small part of the library that can be used by itself". Some other concerns with respect to splitting up the library that we have to think about are:

- what are we going to do about cross dependencies between algorithms and the data types. Concrete example: in the linear-ric branch I'm about to merge in, Polygon gets a function 'isStarShaped' to  test if the polygon is starshaped. The implementation uses Algorithms.Geometry.LinearProgramming though. My intuition might agree that 'polygon' is a 'core' type, but the linear programming algorithm certainly not. So that would suggest that isStarShaped should not go into Polygon, but somewhere else. The question is where? I'm sure that this issue will come up with other functionality as well. (An other example would be a test if two polygons intersect)

- How are we going to organize the sub-packages? Will they become sub-directories in this repository, or will we make separate repositories? In both cases; how will we set up testing? I.e. if making changes in hgeometry-core breaks things in some of the algorithms in some other sub-package I would want to know before merging.
- the Ipe modules are very useful for debugging purposes. We should make sure that that is still easily possible.

I'll make a table with all of the modules, and some of the proposed sub-packages to get a better understanding of what should go where. 

(related to Issue #15 as well I guess)

**Comment by BebeSparkelSparkel** [comment]
I like the idea of keeping things modular.
trigger-travis allows for separate repos by triggering a test if upstream packages has changed https://github.com/plume-lib/trigger-travis
However, sub-packages would be nice because CI would be easy, but we would need to be careful to maintain modularity.

You do have a good point of inter-dependency that I need to think more about

**Comment by alexanderkjeldaas** [comment]
What is the motivation for multiple packages?

**Comment by noinia** [comment]
I've just released a new version of hgeometry and its subpackages on hackage, so I'm closing this.
