### ISSUE TITLE
Single source shortest path

### ISSUE THREAD

**Issue by Lemmih** [noinia/hgeometry#35]
I'd like to add implementation of the single source shortest path for simple polygons. This requires the dual of the triangulation of the polygon, though. I see that `PlanarGraphs` have a `dual` function but I'm at a loss of how to use it. Am I on the right path or should I compute the dual myself? Also, the difference between `PlanarGraph` and `PlaneGraph`. Is `PlaneGraph` a convenience wrapper around `PlanarGraph`?

**Comment by noinia** [comment]
Cool! Computing a shortest path tree/map is pretty high on my list of "algorithms that I would like to add to HGeometry" :). Which one are you planning to implement? The "classical" algorithm by Chazelle et.al [1]? There is also a version of that algorithm by Hershberger and Snoeyink [2] that uses arrays + stacks  rather than finger-trees. That one might be slightly easier.

As for your question on how/what to use with Planar/Plane graphs: 

- A PlanarGraph represents only the combinatorics of a (connected) planar graph,
- A PlaneGraph (which indeed mostly wraps a PlanarGraph) represents (connected) *embedded* graphs, meaning that the vertices have locations, and edges are considered straight line segments, 
- A PlanarSubdivision, which in turn wraps PlaneGraph and supports the graph to be disconnected, have faces with holes, etc.

The polygon triangulation algorithm can give you a PlaneGraph. So you probably want to use something like:

``haskell 
let triangulation = triangulate' myPolygon 
    dualGraph    = triangulation^.graph.dual 
    dualTree       = Algorithms.Graph.dfs dualGraph
in dualTree 
```
to get a Data.Tree with the vertex-ids's (representing the triangles) in the dual graph. I think you get those as 'VertexId s Dual's, so you might have to wrap them in a 'FaceId' to turn them into 'FaceId's compatible with the triangulation though. (I.e. you can then use the FaceId's to query the triangulation for the actual triangles etc). I'm hoping that that helps you on the way a bit? If not let me know then I can maybe give a more concrete example.

Random remark 1: I Guess the API for PlanarGraphs/PlaneGraphs can use some further improvements. If you encounter something that you think should be there/should be different etc. let me know! :) 

Random remark 2: There are actually plenty of algorithms that require as input a *triangulated polygon*. So I think it actually makes sense to have a proper 'TriangulatedPolygon' type. Probably something that wraps up the 'PlaneGraph' that we get from triangulating it, mabye together with the dual tree in some convenient DS. If you have any thoughts about this/what you think would be most convenient there any input would be welcome :). 

[1] https://link.springer.com/article/10.1007/BF01840360
[2] https://link.springer.com/chapter/10.1007/BFb0028273

**Comment by Lemmih** [comment]
I've already implemented the algorithm from the first paper with finger trees (but using my own triangulation and dual-tree code).

Ah, that way of computing the dual tree looks neat. I'll play around with it.

**Comment by Lemmih** [comment]
Your snippet works but is there an easy way to remove the outer face? In the code below, I have a triangulation where face `3` is connected to face `1` and `2`, and face `2` is also connected to face `4`. I'd like a tree where face `3` goes to `[1,2]` and face `2` goes to `[4]`.
```
let triangulation = triangulate' Proxy poly
    dualGraph     = triangulation^.graph.dual 
    dualTree      = dfs dualGraph (VertexId 3)
in putStrLn $ drawTree (fmap show dualTree)
```
```
VertexId 3
|
`- VertexId 2
   |
   `- VertexId 0
      |
      +- VertexId 1
      |
      `- VertexId 4
```

As an unrelated question, what is the `s` parameter for `PlanarGraph`? It appears to be used as a phantom type for `Dart`s but I can't see why.

**Comment by noinia** [comment]
about the outerface: Hmm good question. One option would be to make the dfs support ignoring 'marked' nodes. That way we could mark the vertex representing the outer face, causing it to be skipped.

about the s parameter: it is indeed a phantom type meant to help you avoid indexing in the wrong planar subdivision. The idea is similar to the runST machinery (but here you have additional guarantees since the s is universally quantified). E.g. if you have two planar subdivisions around, say A and B and you have a dart from/into subdivision A (i.e. whose s parameter is tagged with A), the idea is that you cannot use it to accidentally use it to index in subdivision B.
