### ISSUE TITLE
exception with inPolygon

### ISSUE THREAD

**Issue by tonymorris** [noinia/hgeometry#4]
Hello,
I am using this revision 941b9ca0dacc410d54eabe64d312bd5ea1fed724 and trying to run these tests:

https://github.com/noinia/hgeometry/blob/941b9ca0dacc410d54eabe64d312bd5ea1fed724/src/Data/Geometry/Polygon.hs#L170

but on this test:

    point2 5 13 `inPolygon` simplePoly

I see an exception:

    CallStack (from HasCallStack):
      error, called at src/Data/Geometry/SubLine.hs:60:26

This is caused by a custom `fromJust`

https://github.com/noinia/hgeometry/blob/941b9ca0dacc410d54eabe64d312bd5ea1fed724/src/Data/Geometry/SubLine.hs#L60

**Comment by noinia** [comment]
Thanks for reporting this. Somehow I had locally fixed it earlier, but forgot to commit it. It should work again now. 

This also reminds me I should really make sure that travis builds properly again, and extend my testcases, and ... ;)

**Comment by tonymorris** [comment]
I applied ec2fe282dbd66a1c995a898c106ec9243a450d05 but still have the same problem.

Is there some other thing to update?

**Comment by noinia** [comment]
Hmm.  I recently made some changes to the intersection testing code, so I assumed that was the problem. On my local machine, running GHC 7.10, all my tests succeed, and [https://travis-ci.org/noinia/hgeometry/jobs/182718937#L3045](the travis) build seems to suggest that also on 8 the Polygon tests should succeed. 

Are you running the tests using a different numeric type by any chance? In particular, I can get  the exception you have by using Doubles rather than Rationals: 

```
simplePolyRat :: SimplePolygon () Rational
simplePolyRat = SimplePolygon . C.fromList . map ext $ [ point2 0 0
                                                        , point2 10 0
                                                        , point2 10 10
                                                        , point2 5 15
                                                        , point2 1 11
                                                        ]



simplePolyDouble :: SimplePolygon () Double
simplePolyDouble = SimplePolygon . C.fromList . map ext $ [ point2 0 0
                                                        , point2 10 0
                                                        , point2 10 10
                                                        , point2 5 15
                                                        , point2 1 11
                                                        ]
```
```
λ> point2 5 13 `inPolygon` simplePolyRat
Inside
λ> point2 5 13 `inPolygon` simplePolyDouble
*** Exception: toOffset: Nothing
```
If so: the problem is that the code for checking if a point lies on a d-dimensional (sub)line is a bit fragile. In particular, it requires exact numeric computations. When using doubles the computations are "rounded", causing the Nothing case to show up. If you do the math (with real numbers) you can show that the Nothing case cannot show up. 

For two-dimensional stuff there is a different way of testing if a point lies on a (sub)line that is probably a bit more robust to such numerical errors. For this particular example that would probably fix the problem, but that still cannot guarantee correctness in general. 

Can you verify if this is the problem? If so, and if you want, I can see if I can specialize the 2d on-line test, but the proper fix would be to use a different number type.

**Comment by tonymorris** [comment]
Yeah I didn't have a type on the top-level expression so it was defaulting to `Double`. I wasn't aware that would make a difference.
