### ISSUE TITLE
Could 'Vector d' be an instance of Num?

### ISSUE THREAD

**Issue by Lemmih** [noinia/hgeometry#90]
Is there's a mathematical reason why Vectors aren't in Num?

**Comment by noinia** [comment]
I think multiplication would be confusing / not what you want. I assume we would want pointwise addition. To be consistent you would then also want pointwise multiplication (so that v + v = 2*v). However, on the other hand you want to treat vectors like Matrices, but then multiplication is not the same as pointwise multiplication.

**Comment by Lemmih** [comment]
I'd like to treat `Vector 2` as a `V2` which does pointwise multiplication and has completely separate operators for matrix multiplication. Right now, scaling a `Point` or a `Vector` is not straight forward. If `V2` can have a `Num` instance, can't we do the same for `Vector` without causing confusion?

**Comment by noinia** [comment]
Is

```haskell
p .+^ v
u ^+^ v
s *^ v
s *^ p 
scaleBy v p 
```
where p is a point, u and v are vectors, and s is a scalar really so bad/weird? I actually like that these operators force me to think about what I'm doing exactly. Moreover, scaling some vector v with some arbitrary vector u (= pointwise multiplication) is somehow strange enough that I think it is probably good to be explicit about that.

**Comment by Lemmih** [comment]
Ah, I hadn't seen the Transformation module. That makes things a lot easier.
